### ISSUE TITLE
Update commands to match up with "version control with Git" course

### ISSUE THREAD

**Issue by JezSw** [ukaea-rse-training/archived-python-intermediate-development#8]
The "version control with Git" course has changed to use instructions such as switch rather than checkout. This should be reflected in this course where possible.

**Comment by bielsnohr** [comment]
Thanks for raising this @JezSw . The move towards using `git switch` has been addressed in the upstream version: https://github.com/carpentries-incubator/python-intermediate-development/pull/264 .

I suppose we need to check if there is any need for using `git restore`. Since we are going to move to more closely tracking the upstream version, I will raise an issue there and close this one.

**Comment by bielsnohr** [comment]
Just did a quick search through the course material, and there doesn't appear to be a situation where `git restore` would be needed. There is no use of `git checkout` nor `git reset`, so I think we are all good on this front.
